server:
  port: 8084

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/DeveUp/pastley-backend
          search-paths: pastley-config-data
  application:
    name: pastley-config-service
