server:
  port: 8084
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/DeveUp/pastley-backend
          search-paths: pastley-config-data
  application:
    name: pastley-config-service
config:
  security:
    oauth:
      client:
        id: frontendapp
        secret: 12345
      jwt:
        key: algun_codigo_secreto_aeiou
