server:
  port: 8080
#EUREKA 
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
#SPRING
spring:
  cloud:
    #GATEWAY
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: pastley-sale
          uri: lb://pastley-sale
          predicates:
            - Path=/sale/**,/saleDetail/**,/method/**
        - id: pastley-user
          uri: lb://pastley-user
          predicates:
            - Path=/person/**,/user/**